[tasks.dx-run-desktop]
command = "dx"
args = ["serve", "--platform", "desktop"]

[tasks.tailwind-build]
command = "bun"
args = ["tailwindcss", "-i", "./input.css", "-o", "./public/tailwind.css"]

[tasks.cargo-run]
command = "cargo"
args = ["run"]

[tasks.run]
dependencies = ["tailwind-build", "cargo-run"]

